### PR TITLE
Feature/2.1 search within

### PR DESCRIPTION
**Pull request by jabrah**
Fix for the weirdness where the expansion search boxes would hide themselves when expanded. On `bindEvents()` function was called twice on initialization, once in `init` directly, once from the `render` call. I changed it to be called only when rendered for the first time.

The Git comparison for this branch and yours will have a lot of red because I also made code style changes. Just me being nitpicky :)
- Indent changed to 2 spaces for all indents, was mostly 4 spaces before
- Normalized white spaces: eliminate trailing white spaces, have empty line between functions, etc

If the code style changes are not wanted/needed, I can close this PR and resubmit with previous code style.

### CODE REVIEW

**Comment by jabrah** [comment]
Oh, looks like I included a bunch of other commits at the front of IIIF/master as well...such is life, working with several different forks

Current IIIF/master should be only bug fixes, so it should be fine to include. Up to you

**Comment by jeffreycwitt** [comment]
After accepting this pull request, I think something screwing might have
happened because the "saving state" part of mirador that adds the "hash"
(e.g. #a4b07697-547d-496b-b6ea-33249014f59e) to the URL stopped working.

I made another branch representing the state before the merge.

https://github.com/jeffreycwitt/mirador/tree/feature/2.1-search-within-before-merge

I wonder if we should re-make your changes to the expanded menu toggle and
style fixes to this branch and avoid the extra commits we added with the
previous pull request.

The branch with the accepted pull request is still here at:
https://github.com/jeffreycwitt/mirador/tree/feature/2.1-search-within

Let me know what you think.
jw

On Fri, Apr 8, 2016 at 1:45 PM, jabrah notifications@github.com wrote:

> Oh, looks like I included a bunch of other commits at the front of
> IIIF/master as well...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jeffreycwitt/mirador/pull/3#issuecomment-207533684

## 

Dr. Jeffrey C. Witt
Philosophy Department
Loyola University Maryland
4501 N. Charles St.
Baltimore, MD 21210
www.jeffreycwitt.com

**Comment by jeffreycwitt** [comment]
Ha, nevermind, I saw that you just changed the saveSettings to false, like so: `'saveSession' : false.`

Disregard my earlier post.

:)

**Comment by jeffreycwitt** [comment]
Final post, I promise. I took your changes to searchTab.js and added them to the the code before I accepted this pull request.. I then renamed this branch to 2.1-search-within and deleted the branch that had the accepted pull request. The reason I did this was so that I could include your changes to the searchTab.js but get rid of all the earlier commits. I think the earlier commits will make it harder for us to stay in sync with upstream 2.1.

**Pull request merged**
